version: '2'
services:
  netgear-scrapers:
    image: hardenrm/isptracker
    networks:
      - default
    container_name: isptracker
    volumes:
      - '/storage/docker/isptracker/isp-outage-tracker.conf:/app/isp-outage-tracker.conf:z'
    restart: unless-stopped

networks:
  default:
    external: true